PREFIX sdb: <https://skr3.nlm.nih.gov/SemMedDB/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

# Comorbidity test, i.e., diseases that coexist with a form of asthma, both linked to same set of genes
#
SELECT DISTINCT  ?primary_disease  ?comorbidity WHERE 
{
	_:gene
		rdf:type sdb:gngm  ;
		sdb:associated_with ?asthma, ?disease .

	?asthma 
		rdf:type sdb:Asthma ;
        rdfs:label ?primary_disease  .
        
    ?disease
		rdf:type sdb:dsyn ;
		sdb:coexists_with ?asthma ;
        rdfs:label ?comorbidity ;
		# Has not been classified as athma
		FILTER NOT EXISTS { ?disease rdf:type sdb:Asthma  }

} ORDER BY ?primary_disease

