PREFIX sdb: <https://skr3.nlm.nih.gov/SemMedDB/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

select distinct ?gene_label where {
    #graph <virtual://semmeddb>{
        ?disease 
            rdf:type sdb:dsyn ; # Disease
            rdfs:label ?d_label 
            filter (matches(?d_label, "COPD") || ?d_label = "Asthma")
        ?gene 
            rdf:type sdb:gngm ;# Gene
            sdb:associated_with ?disease ;
            rdfs:label ?gene_label .
  #}
}
