PREFIX sdb: <https://skr3.nlm.nih.gov/SemMedDB/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>


# stardog query execute --reasoning semmeddb queries/genes_asthma_reliable.rq 

SELECT DISTINCT ?gene_label ?gene WHERE 
{
	 ?asthma rdf:type sdb:Asthma .
        ?gene
			sdb:associated_with ?asthma ;
            rdf:type sdb:gngm ;# Gene
            rdfs:label ?gene_label .
        ?predication
            rdf:type sdb:ReliablePredication ;
            rdf:subject ?gene ;
            rdf:predicate sdb:associated_with ;
            rdf:object ?asthma .
} 
ORDER BY ?gene_label
