PREFIX sdb: <https://skr3.nlm.nih.gov/SemMedDB/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

# Are there gene entities missing a link to the NCBI gene database?

SELECT  ?gene_label ?gene WHERE {
	?gene 
		rdf:type sdb:gngm ;# Gene
		rdfs:label ?gene_label . 
		FILTER NOT EXISTS { 
			?gene sdb:gene _:missing 
		}
} ORDER BY ?gene_label
