PREFIX sdb: <https://skr3.nlm.nih.gov/SemMedDB/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX spa: <tag:stardog:api:analytics:>

# Incomplete
# see: https://www.stardog.com/docs/#_similarity_search
INSERT {
  GRAPH spa:model {
	sdb:diseaseSimilarityModel
		rdf:type spa:SimilarityModel ;
		spa:parameters [
			spa:minClusterSize 20 ;
        ] ;
		spa:arguments (?x ?y ?z) ;
        spa:predict ?what .
  }
}
WHERE {
   ?disease rdf:type ?x ;
          :y ?y ;
          :z ?z ;
          :w ?what .
}

